### ISSUE TITLE
Auto-expand leagues when only following 1 team

### ISSUE THREAD

**Issue by jorp** [sereneblue/gnome-shell-extension-colosseum#2]
It would be nice to auto-expand the league listing when only 1 team is followed per league. This would save one click per league and allow users to get a faster glance of ongoing/scheduled games.

**Comment by sereneblue** [comment]
Hi @jorp, this sounds like a good idea. The current widget used to display scores only allows one sub item to be open at a time. It also doesn't seem to support opening programmatically so that the scores appear when opening the panel menu. I'll do some testing to see if this is something that can be added. If all goes well, I can add a "compact" mode to reduce the number of clicks needed to see scores.

**Comment by sereneblue** [comment]
@jorp I've added compact mode in v5, shown in the first screenshot of the readme. Thanks for the idea!
