### ISSUE TITLE
Option to move Colosseum location in top bar

### ISSUE THREAD

**Issue by Latnook** [sereneblue/gnome-shell-extension-colosseum#8]
Hi, can you please add the option to move the location of the extension in GNOME's top bar? It can only be located in the right side and I want to move it to the left side of the top bar.

Thank you.

**Comment by sereneblue** [comment]
Hi @Latnook, 

Sure. I'll push out an update soon.

**Comment by Latnook** [comment]
Thank you for the added feature. However, I have been trying to make Colosseum stay in the position I want in the top bar by changing the position variable in extension.js and the extension started to move to the other side of the panel. It would be very helpful if you'd also add a position offset option in Colosseum's preferences.

Thank you very much!

**Comment by sereneblue** [comment]
The line responsible for the position in the left/right of the top bar is:
`boxes[position].insert_child_at_index(this.container, 1);`

You'd have to change the index number (1). 

Do you want Colosseum in the left corner? The Activities button and the current active program make dealing with the left side a little more cumbersome, so by default I set it so that it's 
[Activities: 0] [Colosseum: 1] [Application: 2].

**Comment by Latnook** [comment]
Thank you. I changed it to the position I wanted. I changed the wrong variable previously.

From Israel with Love,
Ariel Palatnik
IT technician at Rambam Healthcare Campus
+972544474948
"The real danger is not that computers will begin to think like men, but that men will begin to think like computers." -Sydney Harris (Journalist)

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------
